# link container on quay with qiime2
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
arguments = $(netid) $(project)
executable = 01_demux.sh
home_path = /home/$(netid)/$(project)

#state path to input files
transfer_input_files = \
  $(home_path)/00_pipeline_inputs/seqs/reverse.fastq.gz, \
  $(home_path)/00_pipeline_inputs/seqs/forward.fastq.gz, \
  $(home_path)/00_pipeline_inputs/seqs/barcodes.fastq.gz, \
  $(home_path)/00_pipeline_inputs/sample-metadata.tsv

#state the output files
transfer_output_files = demux.qza, demux.qzv

#remap outputs to desired location
transfer_output_remaps = \
 "demux.qza = $(home_path)/01_import-demux/demux.qza; \
  demux.qzv = $(home_path)/01_import-demux/demux.qzv "

#create log/err/out files
log = logs/01_demux$(cluster).log
error = logs/01_demux$(cluster).err
output = logs/01_demux$(cluster).out

#set requirements
requirements = (HasCHTChome == true) && (HasChtcProjects == true) && (OpSysMajorVer > 7) 

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
