#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 02_dada2_qc.sh

home_path = /home/$(netid)/$(project)

#state path to input files
transfer_input_files = \
  $(home_path)/01_import-demux/demux.qza

#state the output files
transfer_output_files = rep-seqs.qza, table.qza, stats.qza, stats.qzv, extracted-feature-file.tar.gz

#remap outputs to desired location
transfer_output_remaps = \
  "rep-seqs.qza = $(home_path)/02_dada2_qc/rep-seqs.qza; \
  table.qza = $(home_path)/02_dada2_qc/table.qza; \
  stats.qza = $(home_path)/02_dada2_qc/stats.qza; \
  stats.qzv = $(home_path)/02_dada2_qc/stats.qzv; \
  extracted-feature-file.tar.gz = $(home_path)/02_dada2_qc/extracted-feature-file.tar.gz"

#create log/err/out files
log = logs/02_dada2_qc$(cluster).log
error = logs/02_dada2_qc$(cluster).err
output = logs/02_dada2_qc$(cluster).out

#set requirements
requirements = (HasCHTChome == true) && (HasChtcProjects == true) && (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue
