#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 05_abdiv.sh
home_path = /home/$(netid)/$(project)

arguments = $(column) $(request_cpus)

#state path to input files
transfer_input_files = \
  $(home_path)/04_phytree/rooted-tree.qza, \
  $(home_path)/02_dada2_qc/table.qza, \
  $(home_path)/00_pipeline_inputs/sample-metadata.tsv

#state the output files
transfer_output_files = diversity-core-metrics-phylogenetic.tar.gz

#remap outputs to desired location
transfer_output_remaps = "diversity-core-metrics-phylogenetic.tar.gz = $(home_path)/05_abdiv/diversity-core-metrics-phylogenetic.tar.gz"
   
#create log/err/out files
log = logs/05_abdiv$(cluster).log
error = logs/05_abdiv$(cluster).err
output = logs/05_abdiv$(cluster).out

#set requirements
requirements = (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 16
request_memory = 12GB
request_disk = 12GB

queue
