#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 07_taxonomy.sh
arguments = $(netid) $(project) $(db)
home_path = /home/$(netid)/$(project)

#state path to input files
transfer_input_files = \
  $(home_path)/02_dada2_qc/rep-seqs.qza, \
  $(home_path)/02_dada2_qc/table.qza, \
  $(home_path)/00_pipeline_inputs/sample-metadata.tsv

#state the output files
transfer_output_files = taxonomy.qza, taxonomy.qzv, taxa-bar-plots.qzv

#remap outputs to desired location
transfer_output_remaps = "taxonomy.qza = $(home_path)/07_taxonomy/taxonomy.qza; \
  taxonomy.qzv = $(home_path)/07_taxonomy/taxonomy.qzv; \
  taxa-bar-plots.qzv = $(home_path)/07_taxonomy/taxa-bar-plots.qzv"

#create log/err/out files
log = logs/07_taxonomy$(cluster).log
error = logs/07_taxonomy$(cluster).err
output = logs/07_taxonomy$(cluster).out

#set requirements
requirements = (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 20GB
request_disk = 20GB

queue
