#link container 
container_image = docker://quay.io/qiime2/amplicon:2025.4

#reference sh script
executable = 09_final-files.sh
home_path = /home/$(netid)/$(project)

transfer_input_files = $(home_path)/02_dada2_qc/table.qza , $(home_path)/07_taxonomy/taxonomy.qza
transfer_output_files = final_files_output/otu_table.tsv, final_files_output/taxonomy.tsv
transfer_output_remaps = "final_files_output/otu_table.tsv=$(home_path)/09_final-files/otu_table.tsv, final_files_output/taxonomy.tsv=$(home_path)/09_final-files/taxonomy.tsv"

arguments = $(netid) $(project)
 
#create log/err/out files
log = logs/09_final-files_$(cluster).log
error = logs/09_final-files_$(cluster).err
output = logs/09_final-files_$(cluster).out

#set requirements
requirements = (OpSysMajorVer > 7)

#make requests and queue
request_cpus = 8
request_memory = 12GB
request_disk = 12GB

queue

